image: node:23-bullseye

stages:
  - install
  - test
  - build
  - package
  - notify

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - set -e
    - echo "=== Début du job install ==="
    - echo "=== Installation des dépendances ==="
    - npm install

test:
  stage: test
  dependencies:
    - install
  script:
    - set -e
    - echo "=== Début du job test ==="
    - echo "=== Lancement des tests ==="
    - npm test -- --watchAll=false

build:
  stage: build
  dependencies:
    - install
  script:
    - set -e
    - echo "=== Début du job build ==="
    - echo "=== Build de l'application React ==="
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 2h

package:
  stage: package
  dependencies:
    - build
  script:
    - set -e
    - echo "=== Début du job package ==="
    - echo "=== Packaging des artefacts ==="
    - tar -czf react-build.tar.gz build
    - echo "Trigger Jenkins $(date)" > trigger-jenkins.txt
  artifacts:
    paths:
      - react-build.tar.gz
      - trigger-jenkins.txt
    expire_in: 2h

notify:
  stage: notify
  script:
    - set -e
    - echo "=== Début du job notify ==="
    - echo "Pipeline GitLab terminée, envoi mail..."
    - echo "Pipeline CI GitLab (ReactJS) terminée" | mail -s "CI GitLab terminée" miguel.fenerol@ynov.com
  when: always
